name: Response Time CI
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
jobs:
  response-time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.39.0
        with:
          token: ${{ secrets.GH_PAT }}
          command: "response-time"
